name: DiaDem
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - mscorefonts=0.0.1=3
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - python=3.10.15=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==0.34.1
      - aiodns==3.2.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.11.0
      - anyio==4.6.2.post1
      - apscheduler==3.10.4
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==24.2.0
      - audioread==3.0.1
      - av==13.1.0
      - backcall==0.2.0
      - beartype==0.19.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - blinker==1.9.0
      - cachetools==4.2.4
      - cchardet==2.1.7
      - certifi==2021.10.8
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - cityhash==0.2.4.post11
      - click==8.1.7
      - cloudpickle==3.1.0
      - colorama==0.4.6
      - compressed-tensors==0.8.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - dapr==1.14.0
      - dapr-ext-fastapi==1.14.0
      - dask==2024.12.1
      - datasets==3.1.0
      - dbpool==1.2.1
      - decorator==4.4.2
      - decord==0.6.0
      - deepspeed==0.16.2
      - defusedxml==0.7.1
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - docopt==0.6.2
      - docstring-parser==0.16
      - dsc-auth==0.1.18
      - einops==0.8.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastapi==0.115.5
      - fastjsonschema==2.21.1
      - ffmpeg-python==0.2.0
      - filelock==3.13.1
      - fire==0.7.0
      - flash-attn==2.7.0.post2
      - flask==3.1.0
      - fonttools==4.55.0
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - ftfy==6.3.1
      - func-timeout==4.3.5
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gguf==0.10.0
      - google-api-core==2.23.0
      - google-auth==2.36.0
      - google-cloud-aiplatform==1.71.1
      - google-cloud-bigquery==3.27.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.13.1
      - google-cloud-storage==2.18.2
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - grpc-google-iam-v1==0.13.1
      - grpcio==1.68.0
      - grpcio-reflection==1.48.2
      - grpcio-status==1.68.0
      - h11==0.14.0
      - h5py==3.12.1
      - hf-xet==1.1.4
      - hickle==5.0.3
      - hiredis==2.4.0
      - hjson==3.1.0
      - httpcore==1.0.6
      - httptools==0.6.4
      - httpx==0.27.2
      - huggingface-hub==0.33.0
      - humanize==4.11.0
      - icecream==2.1.3
      - idna==3.10
      - imageio==2.36.0
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.5.0
      - infra-component==1.4.7
      - infra-framework==1.17.10
      - infra-kconf==1.1.3
      - infra-kess==1.1.5
      - infra-keycenter==1.1.1
      - infra-storage==1.3.1
      - install==1.3.5
      - interegular==0.3.3
      - iopath==0.1.10
      - ipdb==0.13.13
      - ipython==8.12.3
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.3
      - jiter==0.7.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-pygments==0.3.0
      - kazoo==2.10.0
      - kiwisolver==1.4.7
      - ks-kafka-python==2.0.3
      - lark==1.2.2
      - lazy-loader==0.4
      - levenshtein==0.26.1
      - librosa==0.11.0
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.6
      - locket==1.0.0
      - lxml==4.9.4
      - lz4==3.1.10
      - markupsafe==2.1.5
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mergedeep==1.3.4
      - mistral-common==1.5.1
      - mistral-inference==1.5.0
      - mistune==3.1.3
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgpack-numpy==0.4.8
      - msgspec==0.18.6
      - multidict==6.1.0
      - multiprocess==0.70.18
      - mysql-connector-python==8.0.31
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.3
      - numba==0.60.0
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - nvitop==1.3.2
      - omegaconf==2.3.0
      - open-clip-torch==2.29.0
      - openai==1.54.3
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - openpyxl==3.1.5
      - outlines==0.0.46
      - packaging==24.1
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parameterized==0.9.0
      - parso==0.8.4
      - partd==1.4.2
      - partial-json-parser==0.2.1.1.post4
      - pathos==0.3.4
      - peft==0.14.0
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pipreqs==0.5.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - portalocker==3.0.0
      - pox==0.3.6
      - ppft==1.7.7
      - prettytable==2.5.0
      - proglog==0.1.10
      - prometheus-client==0.21.0
      - prometheus-fastapi-instrumentator==7.0.0
      - prompt-toolkit==3.0.48
      - propcache==0.2.0
      - proto-plus==1.25.0
      - protobuf==3.20.0
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pyarrow==18.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycares==4.4.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.8
      - pycountry==24.6.1
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydub==0.25.1
      - pygments==2.18.0
      - pyparsing==3.2.0
      - pysmhasher==0.2.5
      - pysoundfile==0.9.0.post1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-levenshtein==0.26.1
      - python-snappy==0.6.1
      - pytorchvideo==0.1.5
      - pytube==15.0.0
      - pytz==2021.3
      - pytz-deprecation-shim==0.1.0.post0
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - qwen-omni-utils==0.0.8
      - qwen-vl-utils==0.0.8
      - rapidfuzz==3.12.2
      - ray==2.38.0
      - redis==4.6.0
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.32.3
      - rpds-py==0.21.0
      - rsa==4.9
      - safetensors==0.4.5
      - scenedetect==0.6.4
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - setuptools-scm==8.1.0
      - shapely==2.0.6
      - simple-parsing==0.1.6
      - six==1.16.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.7
      - soxr==0.5.0.post1
      - sqlparse==0.4.4
      - stack-data==0.6.3
      - starlette==0.41.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - timm==1.0.12
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - tomli==2.0.2
      - toolz==1.0.0
      - torch==2.6.0
      - torchvision==0.21.0
      - tornado==6.4.1
      - tqdm==4.67.0
      - traitlets==5.14.3
      - transformers==4.52.3
      - triton==3.2.0
      - typeguard==4.4.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - tzlocal==4.3.1
      - unpaddedbase64==2.1.0
      - urllib3==1.26.20
      - uvicorn==0.32.0
      - uvloop==0.21.0
      - vertexai==1.71.1
      - vllm==0.6.3
      - watchfiles==0.24.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websockets==13.1
      - werkzeug==3.1.3
      - word2number==1.1
      - xformers==0.0.27.post2
      - xmltodict==0.12.0
      - xxhash==3.5.0
      - yacs==0.1.8
      - yarg==0.1.9
      - yarl==1.17.1
      - zhon==2.1.1
      - zipp==3.20.2
      - zsvision==0.7.12
